---
  title: "Save normalized values as CSV"
output:
  html_document:
  df_print: paged
---

Load packages
```{r}
library("Thermimage")
library("fields")
library("imager")
library("spatstat")
library("exifr")

```

Set configurations
```{r}
# Noise filering
NF = FALSE
# Histogram Equalization
HE = TRUE

# INPUT_PATH_FOLDER
input = "Data/"
# OUTPUT_PATH_FOLDER
output = "2_HE/"
dir.create(file.path(output), showWarnings = FALSE)

# Gassian sigma value for noise filtering
sigma = 0.8

```

Load path images from directory
```{r}
filenames <- list.files(input, pattern="*.JPG", full.names=FALSE)
filenames
```

Read image function
```{r}
# Load original thermal images, convert raw temperature values to estimates and save to output folder. Returns
# values to retrieve the min/max temperature and the calculation of the histogram equalization.
new.read_image <- function(image_file,
                           input_path="", output_path="Output/",
                           NF=FALSE,
                           sigma=0.8,
                           HE=FALSE
) {
  # Create image path
  image_path = paste(input_path, image_file, sep="")

  # Rotate image
  temp_image = rotate270.matrix(readflirJPG(image_path))

  # Noise filtering with gauss filter
  if (NF == TRUE) {
    temp_image =  as.im(temp_image)
    temp_image = blur(temp_image, sigma, bleed=FALSE)
    temp_image =  as.matrix(temp_image)
  }

  # Save temperature image
  saveRDS(temp_image, file = paste(output_path, tools::file_path_sans_ext(image_file), ".RData", sep=""))

  # Return either min or max or every temperature value
  if (HE == TRUE) {
    temp_image
  } else {
    min <- min(temp_image)
    max <- max(temp_image)
    values <- c(min, max)
  }
}
```

Load images
```{r}
glob_temp_range <- unlist(lapply(filenames, new.read_image,
                                 input_path=input,
                                 output_path=output,
                                 NF=NF,
                                 sigma=sigma,
                                 HE=HE))
```

Calculate global min and max values
```{r}
min_temp <- min(glob_temp_range)
max_temp <- max(glob_temp_range)
print(min_temp)
print(max_temp)
```

Calculate ECDF for histogram equalization
```{r}
if (HE == TRUE) {
  f <- ecdf(glob_temp_range)
  hist(glob_temp_range, main=paste("Global Histogram"))
  hist(f(glob_temp_range), main=paste("Global Equalized Histogram"))
} else {
  f <- NULL
}
```

Normalize images (convert temperature values to gray values)
```{r}
new.normalize <- function(image_file, output_path="4_HE_NF/",
                          min, max,
                          HE=FALSE, f_ecdf=NULL) {
  ## Create image path
  image_path = paste(output_path, tools::file_path_sans_ext(image_file), ".RData", sep="")
  temp_image <- readRDS(image_path)
  ## Delete .Rdata file
  unlink(image_path)

  temp_image <- mirror.matrix(temp_image)
  print(temp_image)

  ## Normalize data/apply histogram equalization
  if (HE == TRUE) {
    equalized <- f_ecdf(temp_image)
    #equalized <- as.cimg(equalized, dim=dim(temp_image))
    #plot(equalized, rescale=FALSE, main=paste("Histogram equalized", image_file))
    #save.image(equalized, file=paste(output_path, image_file, sep=""), quality = 1)
    #print(equalized)
    equalized <- round((equalized * (max - min)) + min)
    print(equalized)
    write.csv2(equalized, file=paste(output_path, tools::file_path_sans_ext(image_file), "_he.csv", sep = ""), row.names = FALSE)
  } else {
    temp_image <- (temp_image - min) / (max - min)
    # hist(x=temp_image, main=paste("Histogram of normalized values", image_path), xlab='normalized value')

    ## Plot and save temperature image
    temp_image = as.cimg(temp_image, dim=dim(temp_image))
    save.image(temp_image, file=paste(output_path, image_file, sep=""), quality = 1)
    plot(temp_image, rescale=FALSE)
  }
}
```

Plot normalized images
```{r}
temp = lapply(filenames, new.normalize,
              output_path=output,
              min=min_temp, max=max_temp,
              HE=HE,
              f_ecdf=f)
```
